### ISSUE TITLE
figure and markersize issue on website of test-results

### ISSUE THREAD

**Issue by petravanhoudt** [OSIPI/DCE-DSC-MRI_CodeCollection#125]
Before we submit our manuscript, it would be nice if we can fix one last issue we are having with the size of the markers in the figures of the DCE models. 

They are created with catplot from seaborn. In the notebooks the images look fine, but once they are converted to html it seems as if the markersize is changed. This makes the markers really small. 

Apparently markersize is set with "s=xx" in catplot if you use swarmplot (https://stackoverflow.com/questions/58548261/how-to-change-marker-size-in-seaborn-catplot). Changing this parameter indeed results in changed markersizes in the notebook, but that doesn't result in a change on the website. 

I've tried several things based on suggestions of Zaki (and some googling) to fix the figure size: 
- fix figure size using: sns.set_context("talk", rc={"figure.figsize": (10,8)})
- fix facet size using height and aspect parameters in catplot 
but now I am out of solutions. Anyone else suggestions? 

I started to try things in the extendedToftsmodel notebook, in case you want to have a look.

this is how it looks in the notebook:
![image](https://user-images.githubusercontent.com/1290651/223428937-f402576e-9490-40e9-aaa7-ca69558db9e8.png)

this is how it looks on the website:
![image](https://user-images.githubusercontent.com/1290651/223428749-2bec0a24-2e69-4bc5-bb04-42cb59f16a03.png)

**Comment by notZaki** [comment]
Out of curiosity, which version of seaborn are you using? Should be able to find it out by running 
```python
import seaborn as sns
sns.__version__
```
The website is likely running version `0.12.2`, so maybe that's causing a discrepancy.

**Comment by petravanhoudt** [comment]
I have version 0.11.2. Could that be the reason for the difference? I'll update it anyways.
Or do the changes you did in the styling of the figures make a difference for how they end up in html? Just trying to learn :)

**Comment by mjt320** [comment]
Thanks @notZaki !

**Comment by notZaki** [comment]
@petravanhoudt There were some big changes to catplots and swarmplots with 0.12, so that's why I asked. My local notebook had small markers with 0.12, similar to the old website. So all I did was make the marker size much larger, e.g. 8 -> 100.
