### ISSUE TITLE
Call open for code contributions regarding ' Signal to Concentration'

### ISSUE THREAD

**Issue by petravanhoudt** [OSIPI/DCE-DSC-MRI_CodeCollection#20]
This is a request for python code contributions for the conversion from signal (S) to concentration (C). This can be done as separate steps (S --> R --> C) or as an integrated approach.

For the first version of the library we are interested in the spoiled gradient echo sequqence for DCE and spoiled gradient echo EPI for DSC for the signal models. For the relaxation models we are targeting a linear relation under the assumption of fast water exchange. However, contributions with other signal models or relaxation models are also very much appreciated.

Please go to the documentation for more information about the guidelines for code contributions.

**Comment by sudarshanragu** [comment]
@petravanhoudt can we close this issue since we have code to do this?
