### ISSUE TITLE
Call open for code contributions regarding ' Leakage correction'

### ISSUE THREAD

**Issue by petravanhoudt** [OSIPI/DCE-DSC-MRI_CodeCollection#22]
This is a call for leakage correction methods for DSC-MRI. For the first version of the library we are aiming to facilitate at least theBoxerman-schaminda-weiskoff leakage correction method.

Please note that contributions for other leakage correction methods are also welcome. Go to the documentation folder for the guidelines on new code contributions.

**Comment by sudarshanragu** [comment]
@petravanhoudt I have added code for leakage correction (BSW).
