### ISSUE TITLE
Call open for contributions regarding 'signal extraction (ROI/masking)'

### ISSUE THREAD

**Issue by petravanhoudt** [OSIPI/DCE-DSC-MRI_CodeCollection#24]
We are looking for code contributions to select the time series data from the 4-D S(x,t) data. There are several options to process the data:
- As is, nothing needs to be done: (S(x,t)
- Take average S in a ROI(s) --> output = S(t)
- Use as a 4D dataset (S(x,t)) but only a subset of the voxels are taken into account (for example filter out all voxels outside the brain). 

![DCE pipeline - Signal](https://user-images.githubusercontent.com/1290651/107747768-450c2a80-6d18-11eb-882b-1953d0db8bf7.png)

Please follow the documentation on new code contributions.

**Comment by sunyu0410** [comment]
@petravanhoudt So basically it's either masking (image) or aggregate (ROI) the signal, right?
