### ISSUE TITLE
Finalise T1 testing

### ISSUE THREAD

**Issue by mjt320** [OSIPI/DCE-DSC-MRI_CodeCollection#25]
Finalise testing approach for T1 code, prior to rolling out to other functionality.

**Comment by sudarshanragu** [comment]
@mjt320 I will focus on enhancing the test suite for T1 mapping, since I have already begun writing the test scripts for code already received.

**Comment by petravanhoudt** [comment]
this issue can be closed, isn't it?

**Comment by mjt320** [comment]
Yes, I agree.
