### ISSUE TITLE
Add new contribution

### ISSUE THREAD

**Issue by petravanhoudt** [OSIPI/DCE-DSC-MRI_CodeCollection#36]
Ole Gunnar Johansen is happy to share his DCE code with us: https://github.com/olegjo/Masteroppgave 
link to thesis in case more detail is needed: https://www.duo.uio.no/bitstream/handle/10852/61659/1/thesis_FINAL.pdf 

- contact details have to be added

**Comment by sudarshanragu** [comment]
@petravanhoudt: A branch [https://github.com/OSIPI/DCE-DSC-MRI_CodeCollection/tree/OSJ_OsloU_contribution](url) has been created with code merged from [https://github.com/olegjo/Masteroppgave](url). 

- [x] The directory structure and source code locations have to be updated
- [x] I have not added the contact details yet

**Comment by petravanhoudt** [comment]
Not sure if we need everything from the original contribution? The main code is on the MRIimageAnalysis directory. The others contain data and simulations. What do you think @schudds ?

**Comment by petravanhoudt** [comment]
branch has been merged to develop
