### ISSUE TITLE
test slack-github app

### ISSUE THREAD

**Issue by petravanhoudt** [OSIPI/DCE-DSC-MRI_CodeCollection#45]
To test how the slack issue works.
Did you get a notification @schudds?

**Comment by sudarshanragu** [comment]
@petravanhoudt apologies on the late response :) .. I did get notified when a new issue was opened in slack. However, I dont think I can respond  / add comments from slack.

**Comment by petravanhoudt** [comment]
@schudds, no that is true. I also did not get notifications when comments were placed to other issues. So not sure how useful it is in that case
