### ISSUE TITLE
Visualize results from testing

### ISSUE THREAD

**Issue by petravanhoudt** [OSIPI/DCE-DSC-MRI_CodeCollection#46]
The tests now give a pass/fail output for each test. For scientific reasons, it might be more insightful to compare the measured values with reference values etc. Therefore, I started a branch to explore the options.

As fas as I understood the values are not available from GitActions, so I've added some functionality to save the results in csv files when the tests are being performed. Jupyter lab was used to visualise some results from T1 mapping code. The csv files and notebook are saved in the results dir within test.

Off course, I am aware that there is a lot to be improved, but I was wondering whether the general approach is the way to go with this. Any thoughts? 

Link to branch: https://github.com/OSIPI/DCE-DSC-MRI_CodeCollection/compare/Test_SaveResults

**Comment by petravanhoudt** [comment]
Interestingly, from a scientific point of view, the differences between the linear implementations of VFA fitting for the DRO data were much smaller (i.e. almost identical) compared to their differences with the reference values.

**Comment by mjt320** [comment]
I think this is great @petravanhoudt . Thoughts:
- potentially this is a way to generate reference values (based on average output over contributions) for the tests when we don't have/can't agree on true reference values
- we could easily add execution timing to this
- pretty sure we could automate this using git actions. Just need to figure out how!
- maybe developing/expanding this can be part of the next MS
Will try to have a closer look ahead of our next meeting.

**Comment by petravanhoudt** [comment]
Good suggestion to have this as part of the next MS @mjt320. I think for the paper it would at least be useful to have some more detailed insight in the differences between contributions. That is partly the reason why I started this. Also for users of the library it might help to decide which contribution to use. There is a lot to improve in the notebook (code and visualization wise), also depends a bit on what we want to visualize exactly. Probably that evolves over time.

I have also been thinking about creating and saving figs and then adding them to a new wiki page. But I think in this stage a notebook is more useful way of exploring.

There should be a way to save the execution time in a log file by adding a node to GitActions, but I also haven't looked into it yet.

**Comment by notZaki** [comment]
Great work @petravanhoudt !

The timing information can be obtained by using the `time` module. There are magic commands to get timing information in notebooks, such as by inserting `%%time` at the beginning of the cell (to time the entire cell) or `%time` at the beginning of a line (to time that specific line).

The notebooks and csv output can be generated through GitActions. This was somewhat implemented in the [`demo`](https://github.com/OSIPI/DCE-DSC-MRI_CodeCollection/tree/demo) branch which automatically takes [a notebook like this](https://github.com/OSIPI/DCE-DSC-MRI_CodeCollection/blob/demo/notebooks/T1mapping_QIBAv1.ipynb) and generates a webpage where [the output looks like this](https://notzaki.github.io/osipidemo/T1mapping_QIBAv1.html).

**Comment by mjt320** [comment]
Hi @petravanhoudt,

I've modified the GitActions yaml file so that the CSV files are now created automatically in the repository (your branch only).

I also added a simple timer for @notZaki T1 contributions only.

Would the following GitActions workflow work?
1) run pytest, which generates pass-fail output + the CSV files
2) push these to Github
3) run notebooks, which read in the CSVs and generate summary tables and plots
4) push updated notebooks to Github

Looking forward to chatting about this soon.

**Comment by notZaki** [comment]
@mjt320 
A potential modification is to push the CSV/notebooks to a different branch to avoid merge conflicts (e.g. if someone pushes a commit while GitActions is still running).

This can be taken a step further by pushing the CSV/notebooks to a different repository so that the size of the current repo isn't affected by the outputs.

**Comment by petravanhoudt** [comment]
Thanks @mjt320 and @notZaki for improving this!
@notZaki, apologies for forgetting that you made something similar. I'll have a closer look later, but I think we can merge the approaches. The webpage looks very useful, especially for end users of the library.

**Comment by mjt320** [comment]
Thanks @notZaki, I take your point. I'll probably not do much more on this before the next milestone. I'm happy we've got a way to combine the automated unit testing with reporting of the actual results. Let's have a discussion re. next steps ahead of November.
