### ISSUE TITLE
Rogue folder?

### ISSUE THREAD

**Issue by mjt320** [OSIPI/DCE-DSC-MRI_CodeCollection#49]
src/original/T1_mapping contains a requirements txt file.

I'm not sure it's supposed to be in this location, though?

**Comment by sudarshanragu** [comment]
THat is correct @mjt320. It looks like I may have not pulled the most recent changes to the folder structure on [develop](https://github.com/OSIPI/DCE-DSC-MRI_CodeCollection) when creating my pull request with this [requirements text](https://github.com/OSIPI/DCE-DSC-MRI_CodeCollection/blob/develop/src/original/T1_mapping/MJT_EdinburghUK/requirements.txt) file. The folder containing this file is deprecated and can be removed. 

I can create a new feature request on issues to add requirements file for each unique "feature" by every contributor, if that is okay. This should hopefully fix this issue and also at the same time include all dependencies for each contribution made so far. We could also discuss this at our next meeting if appropriate.

**Comment by mjt320** [comment]
Thanks @schudds. I will remove the folder. Yes, it seems sensible to me to list the requirements for each "feature" somewhere.
