### ISSUE TITLE
build and code coverage badge inactive

### ISSUE THREAD

**Issue by schudds** [OSIPI/DCE-DSC-MRI_CodeCollection#6]
@petravanhoudt , @mjt320 : The build status and code coverage status display unknown status on README.md in Milestone-2. This could potentially have arisen from the repository name change. 

Solution : The updated repository name has to be reflected on Travis and CodeCov.

**Comment by schudds** [comment]
@mjt320, @petravanhoudt : If it is okay with you, I will close this issue as the solution has been implemented. Thanks!

**Comment by notZaki** [comment]
The Travis build badge has to be replaced with Github Actions badge, but I think the badge is made for the default branch which is currently `master` whereas all the test/code is on `Milestone-2` branch.

Would it make sense to rename `Milestone-2` to `main` and make it the default branch? That'll make it easier to get the build status, and I think it's a better landing page than the current `master` branch.

**Comment by mjt320** [comment]
Yep. At the last co-leads meeting we thought that changing the MS2 branch name to "development" would be a good option and this would become our main working branch. To be merged with master periodically once code contributions are reasonably finalised.
