### ISSUE TITLE
Population AIF tests have been removed during one of recent merges into develop

### ISSUE THREAD

**Issue by petravanhoudt** [OSIPI/DCE-DSC-MRI_CodeCollection#67]
In december the tests for population AIF (PopulationAIF_test branch) was merged into develop, but the files seem to have been removed in one of the later commits. 
Can we revert this or should I create a new pull request to merge the branch with develop?

**Comment by mjt320** [comment]
I have a feeling I might have inadvertently caused this. Sorry!
Hopefully, @schudds or @notZaki might be able to fix the mess, otherwise I guess we can copy-paste the missing files back into develop.

**Comment by sudarshanragu** [comment]
@mjt320 , @petravanhoudt I'll take a look at this - we should be able to revert back to the old commit.

**Comment by notZaki** [comment]
I think the simplest solution is to copy over the files into a new commit/branch and then merge into `develop`---there is an open PR that does this.
