### ISSUE TITLE
edit consistency in filenames/folders/functions

### ISSUE THREAD

**Issue by petravanhoudt** [OSIPI/DCE-DSC-MRI_CodeCollection#73]
Check consistency in filenames and folders:
- src/original/McGill_Can should be ZA_McGill_Can
- test file names and functions aren't named in the same way
- filenames of csv files with test results --> consistent with test files?

Please list other inconsistencies below

**Comment by petravanhoudt** [comment]
LCB_BNI should be LCB_BNI_US or USA

**Comment by petravanhoudt** [comment]
change units of parameters according to TF4.2 lexicon.
This includes changes at the level of test files, csv files of test data, and notebooks.

**Comment by mjt320** [comment]
working on this...
