### ISSUE TITLE
DCEModel tests for OG and LCB code run very slowly

### ISSUE THREAD

**Issue by mjt320** [OSIPI/DCE-DSC-MRI_CodeCollection#78]
LCB's code in particular is quite simple.
Does anyone have a guess as to why this is?
Thanks.

**Comment by sunyu0410** [comment]
@mjt320 I notice multiple test files have `OG`. Can you point to the exact files to be examined?

**Comment by mjt320** [comment]
Thanks @sunyu0410 
test_DCEmodels_etofts_OG_MO_AUMC_ICR_RMH
test_DCEmodels_tofts_LCB_BNI
Looking at this again, perhaps the slow execution is just down to the implementations, particularly for the convolution step. Maybe it's not so surprising...

**Comment by sunyu0410** [comment]
> 

@mjt320 Thanks for the info. If it generates the expected outcome, then it probably is not a bug. I've removed the bug label.

**Comment by mjt320** [comment]
Issue resolved
